logfile: './errors.log'
base64_chars: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='
archive_types: ['.zip', '.tar.gz', '.tgz', '.tar.bz2', '.tbz']
excluded: [
        '.jpg', '.jpeg', '.png', '.gif', '.svg',
        '.mp4', '.mp3', '.webm',
        '.ttf', '.woff', '.eot',
        '.css', '.DS_Store',
        '.pdf']
min_key_length: 40
<<<<<<< HEAD
max_key_length: 60
high_entropy_edge: 4.3
=======
max_key_length: 80
>>>>>>> 7608651da9d0e12c3a8eefd21db667792f6b57af
